// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Anchor: typeof import('./../src/components/RoomDetail/RoomTab/Anchor.vue')['default'];
    AnchorInfo: typeof import('./../src/components/RoomDetail/RoomTab/AnchorInfo.vue')['default'];
    Anchors: typeof import('./../src/components/SportsCard/Anchors.vue')['default'];
    AppHeader: typeof import('./../src/components/common/AppHeader.vue')['default'];
    AppHeader_副本: typeof import('./../src/components/common/AppHeader_副本.vue')['default'];
    BaseVirtualList: typeof import('./../src/components/common/BaseVirtualList/src/base-virtual-list.vue')['default'];
    BaseVirtualObserver: typeof import('./../src/components/common/BaseVirtualList/src/base-virtual-observer.vue')['default'];
    BasketballLU: typeof import('./../src/components/RoomDetail/RoomTab/BasketballLU.vue')['default'];
    BasketStatus: typeof import('./../src/components/RoomDetail/RoomTab/components/status/BasketStatus.vue')['default'];
    BsLineUpTable: typeof import('./../src/components/RoomDetail/RoomTab/components/lineup/BsLineUpTable.vue')['default'];
    Chat: typeof import('./../src/components/RoomDetail/RoomTab/Chat.vue')['default'];
    ChatList: typeof import('./../src/components/RoomDetail/RoomTab/components/charts/ChatList.vue')['default'];
    CircleItem: typeof import('./../src/components/RoomDetail/RoomTab/components/status/CircleItem.vue')['default'];
    DefaultImg: typeof import('./../src/components/common/DefaultImg.vue')['default'];
    Emoji: typeof import('./../src/components/common/Emoji.vue')['default'];
    EmptyData: typeof import('./../src/components/common/EmptyData.vue')['default'];
    EventCardLeft: typeof import('./../src/components/RoomDetail/RoomTab/components/status/EventCardLeft.vue')['default'];
    EventCardRight: typeof import('./../src/components/RoomDetail/RoomTab/components/status/EventCardRight.vue')['default'];
    FloatingActionSheet: typeof import('./../src/components/FloatingActionSheet/index.vue')['default'];
    FollowStar: typeof import('./../src/components/SportsCard/FollowStar/index.vue')['default'];
    FootStatus: typeof import('./../src/components/RoomDetail/RoomTab/components/status/FootStatus.vue')['default'];
    GridVirtualScroller: typeof import('./../src/components/common/GridVirtualScroller/index.vue')['default'];
    IconClose: typeof import('./../src/components/LiveStartNotify/IconClose/index.vue')['default'];
    IconLoading: typeof import('./../src/components/common/PullRefresh/IconLoading/index.vue')['default'];
    IconRipple: typeof import('./../src/components/LiveStartNotify/IconRipple/index.vue')['default'];
    JQSTable: typeof import('./../src/components/RoomDetail/RoomTab/components/odds/JQSTable.vue')['default'];
    LineCoach: typeof import('./../src/components/RoomDetail/RoomTab/components/lineup/LineCoach.vue')['default'];
    LineUp: typeof import('./../src/components/RoomDetail/RoomTab/LineUp.vue')['default'];
    LineUpTable: typeof import('./../src/components/RoomDetail/RoomTab/components/lineup/LineUpTable.vue')['default'];
    LivePlayer: typeof import('./../src/components/RoomDetail/RoomTab/components/player/LivePlayer.vue')['default'];
    Lives: typeof import('./../src/components/RoomDetail/RoomTab/Lives.vue')['default'];
    LiveStartNotify: typeof import('./../src/components/LiveStartNotify/index.vue')['default'];
    MatchStatus: typeof import('./../src/components/common/MatchStatus.vue')['default'];
    NavBar: typeof import('./../src/components/common/NavBar.vue')['default'];
    Odds: typeof import('./../src/components/RoomDetail/RoomTab/Odds.vue')['default'];
    PageBox: typeof import('./../src/components/common/PageBox.vue')['default'];
    PageVirtualScroller: typeof import('./../src/components/common/PageVirtualScroller/index.vue')['default'];
    PlayerItem: typeof import('./../src/components/RoomDetail/RoomTab/components/lineup/PlayerItem.vue')['default'];
    PullRefresh: typeof import('./../src/components/common/PullRefresh/index.vue')['default'];
    RoomItem: typeof import('./../src/components/common/RoomItem.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SPFTable: typeof import('./../src/components/RoomDetail/RoomTab/components/odds/SPFTable.vue')['default'];
    SportsCard: typeof import('./../src/components/SportsCard/index.vue')['default'];
    SportsMiniCard: typeof import('./../src/components/SportsCard/SportsMiniCard.vue')['default'];
    SubItem: typeof import('./../src/components/RoomDetail/RoomTab/components/lineup/SubItem.vue')['default'];
    SysLoading: typeof import('./../src/components/SysLoading/index.vue')['default'];
    Tabs: typeof import('./../src/components/common/Tabs.vue')['default'];
    TipBar: typeof import('./../src/components/SportsCard/TipBar.vue')['default'];
    UiCheck: typeof import('./../src/components/common/UiCheck/index.vue')['default'];
    UseImg: typeof import('./../src/components/common/UseImg.vue')['default'];
    VanActionSheet: typeof import('vant/es')['ActionSheet'];
    VanButton: typeof import('vant/es')['Button'];
    VanCircle: typeof import('vant/es')['Circle'];
    VanDatePicker: typeof import('vant/es')['DatePicker'];
    VanDialog: typeof import('vant/es')['Dialog'];
    VanField: typeof import('vant/es')['Field'];
    VanIcon: typeof import('vant/es')['Icon'];
    VanList: typeof import('vant/es')['List'];
    VanLoading: typeof import('vant/es')['Loading'];
    VanNavBar: typeof import('vant/es')['NavBar'];
    VanNoticeBar: typeof import('vant/es')['NoticeBar'];
    VanOverlay: typeof import('vant/es')['Overlay'];
    VanPop: typeof import('vant/es')['Pop'];
    VanPopup: typeof import('vant/es')['Popup'];
    VanProgress: typeof import('vant/es')['Progress'];
    VanPullRefresh: typeof import('vant/es')['PullRefresh'];
    VanSticky: typeof import('vant/es')['Sticky'];
    VanSwipeCell: typeof import('vant/es')['SwipeCell'];
    VanTab: typeof import('vant/es')['Tab'];
    VanTabbar: typeof import('vant/es')['Tabbar'];
    VanTabbarItem: typeof import('vant/es')['TabbarItem'];
    VanTabs: typeof import('vant/es')['Tabs'];
    VantInput: typeof import('vant/es')['tInput'];
    VantTextarea: typeof import('vant/es')['tTextarea'];
    VanUploader: typeof import('vant/es')['Uploader'];
    Verify: typeof import('./../src/components/Verifition/Verify.vue')['default'];
    VerifyPoints: typeof import('./../src/components/Verifition/Verify/VerifyPoints.vue')['default'];
    VerifySlide: typeof import('./../src/components/Verifition/Verify/VerifySlide.vue')['default'];
    VideoLoading: typeof import('./../src/components/VideoLoading/index.vue')['default'];
    VirtualListScroller: typeof import('./../src/components/common/VirtualListScroller/index.vue')['default'];
  }
}
