const countries = [
  {
    countryId: 100042,
    value: '86',
    nameEn: 'China',
    name: '中国',
    acronym: 'CN',
  },
  {
    countryId: 100076,
    value: '852',
    nameEn: 'Hongkong',
    name: '中国香港',
    acronym: '810000',
  },
  {
    countryId: 100105,
    value: '853',
    nameEn: 'Macao',
    name: '中国澳门',
    acronym: '820000',
  },
  {
    countryId: 100174,
    value: '886',
    nameEn: 'Taiwan',
    name: '中国台湾',
    acronym: '710000',
  },
  {
    value: '244',
    nameEn: 'Angola',
    name: '安哥拉',
    acronym: 'AO',
  },
  {
    value: '93',
    nameEn: 'Afghanistan',
    name: '阿富汗',
    acronym: 'AF',
  },
  {
    value: '355',
    nameEn: 'Albania',
    name: '阿尔巴尼亚',
    acronym: 'AL',
  },
  {
    value: '213',
    nameEn: 'Algeria',
    name: '阿尔及利亚',
    acronym: 'DZ',
  },
  {
    value: '376',
    nameEn: 'Andorra',
    name: '安道尔共和国',
    acronym: 'AD',
  },
  {
    value: '1264',
    nameEn: 'Anguilla',
    name: '安圭拉岛',
    acronym: 'AI',
  },
  {
    value: '1268',
    nameEn: 'Antigua and Barbuda',
    name: '安提瓜和巴布达',
    acronym: 'AG',
  },
  {
    value: '54',
    nameEn: 'Argentina',
    name: '阿根廷',
    acronym: 'AR',
  },
  {
    value: '374',
    nameEn: 'Armenia',
    name: '亚美尼亚',
    acronym: 'AM',
  },
  {
    value: '61',
    nameEn: 'Australia',
    name: '澳大利亚',
    acronym: 'AU',
  },
  {
    value: '43',
    nameEn: 'Austria',
    name: '奥地利',
    acronym: 'AT',
  },
  {
    countryId: 100018,
    value: '994',
    nameEn: 'Azerbaijan',
    name: '阿塞拜疆',
    acronym: 'AZ',
  },
  {
    countryId: 100019,
    value: '1242',
    nameEn: 'Bahamas',
    name: '巴哈马',
    acronym: 'BS',
  },
  {
    countryId: 100020,
    value: '973',
    nameEn: 'Bahrain',
    name: '巴林',
    acronym: 'BH',
  },
  {
    countryId: 100021,
    value: '880',
    nameEn: 'Bangladesh',
    name: '孟加拉国',
    acronym: 'BD',
  },
  {
    countryId: 100022,
    value: '1246',
    nameEn: 'Barbados',
    name: '巴巴多斯',
    acronym: 'BB',
  },
  {
    countryId: 100023,
    value: '375',
    nameEn: 'Belarus',
    name: '白俄罗斯',
    acronym: 'BY',
  },
  {
    countryId: 100024,
    value: '32',
    nameEn: 'Belgium',
    name: '比利时',
    acronym: 'BE',
  },
  {
    countryId: 100025,
    value: '501',
    nameEn: 'Belize',
    name: '伯利兹',
    acronym: 'BZ',
  },
  {
    countryId: 100026,
    value: '229',
    nameEn: 'Benin',
    name: '贝宁',
    acronym: 'BJ',
  },
  {
    countryId: 100027,
    value: '1441',
    nameEn: 'Bermuda Is.',
    name: '百慕大群岛',
    acronym: 'BM',
  },
  {
    countryId: 100028,
    value: '591',
    nameEn: 'Bolivia',
    name: '玻利维亚',
    acronym: 'BO',
  },
  {
    countryId: 100029,
    value: '267',
    nameEn: 'Botswana',
    name: '博茨瓦纳',
    acronym: 'BW',
  },
  {
    countryId: 100030,
    value: '55',
    nameEn: 'Brazil',
    name: '巴西',
    acronym: 'BR',
  },
  {
    countryId: 100031,
    value: '673',
    nameEn: 'Brunei',
    name: '文莱',
    acronym: 'BN',
  },
  {
    countryId: 100032,
    value: '359',
    nameEn: 'Bulgaria',
    name: '保加利亚',
    acronym: 'BG',
  },
  {
    countryId: 100033,
    value: '226',
    nameEn: 'Burkina-faso',
    name: '布基纳法索',
    acronym: 'BF',
  },
  {
    countryId: 100034,
    value: '95',
    nameEn: 'Burma',
    name: '缅甸',
    acronym: 'MM',
  },
  {
    countryId: 100035,
    value: '257',
    nameEn: 'Burundi',
    name: '布隆迪',
    acronym: 'BI',
  },
  {
    countryId: 100036,
    value: '237',
    nameEn: 'Cameroon',
    name: '喀麦隆',
    acronym: 'CM',
  },
  {
    countryId: 100037,
    value: '001',
    nameEn: 'Canada',
    name: '加拿大',
    acronym: 'CA',
  },
  {
    countryId: 100038,
    value: '1345',
    nameEn: 'Cayman Is.',
    name: '开曼群岛',
    acronym: 'KY',
  },
  {
    countryId: 100039,
    value: '236',
    nameEn: 'Central African Republic',
    name: '中非共和国',
    acronym: 'CF',
  },
  {
    countryId: 100040,
    value: '235',
    nameEn: 'Chad',
    name: '乍得',
    acronym: 'TD',
  },
  {
    countryId: 100041,
    value: '56',
    nameEn: 'Chile',
    name: '智利',
    acronym: 'CL',
  },
  {
    countryId: 100043,
    value: '57',
    nameEn: 'Colombia',
    name: '哥伦比亚',
    acronym: 'CO',
  },
  {
    countryId: 100044,
    value: '242',
    nameEn: 'Congo',
    name: '刚果',
    acronym: 'CG',
  },
  {
    countryId: 100045,
    value: '682',
    nameEn: 'Cook Is.',
    name: '库克群岛',
    acronym: 'CK',
  },
  {
    countryId: 100046,
    value: '506',
    nameEn: 'Costa Rica',
    name: '哥斯达黎加',
    acronym: 'CR',
  },
  {
    countryId: 100047,
    value: '53',
    nameEn: 'Cuba',
    name: '古巴',
    acronym: 'CU',
  },
  {
    countryId: 100048,
    value: '357',
    nameEn: 'Cyprus',
    name: '塞浦路斯',
    acronym: 'CY',
  },
  {
    countryId: 100049,
    value: '420',
    nameEn: 'Czech Republic',
    name: '捷克',
    acronym: 'CZ',
  },
  {
    countryId: 100050,
    value: '45',
    nameEn: 'Denmark',
    name: '丹麦',
    acronym: 'DK',
  },
  {
    countryId: 100051,
    value: '253',
    nameEn: 'Djibouti',
    name: '吉布提',
    acronym: 'DJ',
  },
  {
    countryId: 100052,
    value: '1890',
    nameEn: 'Dominica Rep.',
    name: '多米尼加共和国',
    acronym: 'DO',
  },
  {
    countryId: 100053,
    value: '593',
    nameEn: 'Ecuador',
    name: '厄瓜多尔',
    acronym: 'EC',
  },
  {
    countryId: 100054,
    value: '20',
    nameEn: 'Egypt',
    name: '埃及',
    acronym: 'EG',
  },
  {
    countryId: 100055,
    value: '503',
    nameEn: 'EI Salvador',
    name: '萨尔瓦多',
    acronym: 'SV',
  },
  {
    countryId: 100056,
    value: '372',
    nameEn: 'Estonia',
    name: '爱沙尼亚',
    acronym: 'EE',
  },
  {
    countryId: 100057,
    value: '251',
    nameEn: 'Ethiopia',
    name: '埃塞俄比亚',
    acronym: 'ET',
  },
  {
    countryId: 100058,
    value: '679',
    nameEn: 'Fiji',
    name: '斐济',
    acronym: 'FJ',
  },
  {
    countryId: 100059,
    value: '358',
    nameEn: 'Finland',
    name: '芬兰',
    acronym: 'FI',
  },
  {
    countryId: 100060,
    value: '33',
    nameEn: 'France',
    name: '法国',
    acronym: 'FR',
  },
  {
    countryId: 100061,
    value: '594',
    nameEn: 'French Guiana',
    name: '法属圭亚那',
    acronym: 'GF',
  },
  {
    countryId: 100062,
    value: '241',
    nameEn: 'Gabon',
    name: '加蓬',
    acronym: 'GA',
  },
  {
    countryId: 100063,
    value: '220',
    nameEn: 'Gambia',
    name: '冈比亚',
    acronym: 'GM',
  },
  {
    countryId: 100064,
    value: '995',
    nameEn: 'Georgia',
    name: '格鲁吉亚',
    acronym: 'GE',
  },
  {
    countryId: 100065,
    value: '49',
    nameEn: 'Germany',
    name: '德国',
    acronym: 'DE',
  },
  {
    countryId: 100066,
    value: '233',
    nameEn: 'Ghana',
    name: '加纳',
    acronym: 'GH',
  },
  {
    countryId: 100067,
    value: '350',
    nameEn: 'Gibraltar',
    name: '直布罗陀',
    acronym: 'GI',
  },
  {
    countryId: 100068,
    value: '30',
    nameEn: 'Greece',
    name: '希腊',
    acronym: 'GR',
  },
  {
    countryId: 100069,
    value: '1809',
    nameEn: 'Grenada',
    name: '格林纳达',
    acronym: 'GD',
  },
  {
    countryId: 100070,
    value: '1671',
    nameEn: 'Guam',
    name: '关岛',
    acronym: 'GU',
  },
  {
    countryId: 100071,
    value: '502',
    nameEn: 'Guatemala',
    name: '危地马拉',
    acronym: 'GT',
  },
  {
    countryId: 100072,
    value: '224',
    nameEn: 'Guinea',
    name: '几内亚',
    acronym: 'GN',
  },
  {
    countryId: 100073,
    value: '592',
    nameEn: 'Guyana',
    name: '圭亚那',
    acronym: 'GY',
  },
  {
    countryId: 100074,
    value: '509',
    nameEn: 'Haiti',
    name: '海地',
    acronym: 'HT',
  },
  {
    countryId: 100075,
    value: '504',
    nameEn: 'Honduras',
    name: '洪都拉斯',
    acronym: 'HN',
  },

  {
    countryId: 100077,
    value: '36',
    nameEn: 'Hungary',
    name: '匈牙利',
    acronym: 'HU',
  },
  {
    countryId: 100078,
    value: '354',
    nameEn: 'Iceland',
    name: '冰岛',
    acronym: 'IS',
  },
  {
    countryId: 100079,
    value: '91',
    nameEn: 'India',
    name: '印度',
    acronym: 'IN',
  },
  {
    countryId: 100080,
    value: '62',
    nameEn: 'Indonesia',
    name: '印度尼西亚',
    acronym: 'ID',
  },
  {
    countryId: 100081,
    value: '98',
    nameEn: 'Iran',
    name: '伊朗',
    acronym: 'IR',
  },
  {
    countryId: 100082,
    value: '964',
    nameEn: 'Iraq',
    name: '伊拉克',
    acronym: 'IQ',
  },
  {
    countryId: 100083,
    value: '353',
    nameEn: 'Ireland',
    name: '爱尔兰',
    acronym: 'IE',
  },
  {
    countryId: 100084,
    value: '972',
    nameEn: 'Israel',
    name: '以色列',
    acronym: 'IL',
  },
  {
    countryId: 100085,
    value: '39',
    nameEn: 'Italy',
    name: '意大利',
    acronym: 'IT',
  },
  {
    countryId: 100086,
    value: '225',
    nameEn: 'Ivory Coast',
    name: '科特迪瓦',
    acronym: 'KT',
  },
  {
    countryId: 100087,
    value: '1876',
    nameEn: 'Jamaica',
    name: '牙买加',
    acronym: 'JM',
  },
  {
    countryId: 100088,
    value: '81',
    nameEn: 'Japan',
    name: '日本',
    acronym: 'JP',
  },
  {
    countryId: 100089,
    value: '962',
    nameEn: 'Jordan',
    name: '约旦',
    acronym: 'JO',
  },
  {
    countryId: 100090,
    value: '855',
    nameEn: 'Kampuchea (Cambodia )',
    name: '柬埔寨',
    acronym: 'KH',
  },
  {
    countryId: 100091,
    value: '327',
    nameEn: 'Kazakstan',
    name: '哈萨克斯坦',
    acronym: 'KZ',
  },
  {
    countryId: 100092,
    value: '254',
    nameEn: 'Kenya',
    name: '肯尼亚',
    acronym: 'KE',
  },
  {
    countryId: 100093,
    value: '82',
    nameEn: 'Korea',
    name: '韩国',
    acronym: 'KR',
  },
  {
    countryId: 100094,
    value: '965',
    nameEn: 'Kuwait',
    name: '科威特',
    acronym: 'KW',
  },
  {
    countryId: 100095,
    value: '331',
    nameEn: 'Kyrgyzstan',
    name: '吉尔吉斯坦',
    acronym: 'KG',
  },
  {
    countryId: 100096,
    value: '856',
    nameEn: 'Laos',
    name: '老挝',
    acronym: 'LA',
  },
  {
    countryId: 100097,
    value: '371',
    nameEn: 'Latvia',
    name: '拉脱维亚',
    acronym: 'LV',
  },
  {
    countryId: 100098,
    value: '961',
    nameEn: 'Lebanon',
    name: '黎巴嫩',
    acronym: 'LB',
  },
  {
    countryId: 100099,
    value: '266',
    nameEn: 'Lesotho',
    name: '莱索托',
    acronym: 'LS',
  },
  {
    countryId: 100100,
    value: '231',
    nameEn: 'Liberia',
    name: '利比里亚',
    acronym: 'LR',
  },
  {
    countryId: 100101,
    value: '218',
    nameEn: 'Libya',
    name: '利比亚',
    acronym: 'LY',
  },
  {
    countryId: 100102,
    value: '423',
    nameEn: 'Liechtenstein',
    name: '列支敦士登',
    acronym: 'LI',
  },
  {
    countryId: 100103,
    value: '370',
    nameEn: 'Lithuania',
    name: '立陶宛',
    acronym: 'LT',
  },
  {
    countryId: 100104,
    value: '352',
    nameEn: 'Luxembourg',
    name: '卢森堡',
    acronym: 'LU',
  },
  {
    countryId: 100106,
    value: '261',
    nameEn: 'Madagascar',
    name: '马达加斯加',
    acronym: 'MG',
  },
  {
    countryId: 100107,
    value: '265',
    nameEn: 'Malawi',
    name: '马拉维',
    acronym: 'MW',
  },
  {
    countryId: 100108,
    value: '60',
    nameEn: 'Malaysia',
    name: '马来西亚',
    acronym: 'MY',
  },
  {
    countryId: 100109,
    value: '960',
    nameEn: 'Maldives',
    name: '马尔代夫',
    acronym: 'MV',
  },
  {
    countryId: 100110,
    value: '223',
    nameEn: 'Mali',
    name: '马里',
    acronym: 'ML',
  },
  {
    countryId: 100111,
    value: '356',
    nameEn: 'Malta',
    name: '马耳他',
    acronym: 'MT',
  },
  {
    countryId: 100113,
    value: '596',
    nameEn: 'Martinique',
    name: '马提尼克',
    acronym: 'MQ',
  },
  {
    countryId: 100114,
    value: '230',
    nameEn: 'Mauritius',
    name: '毛里求斯',
    acronym: 'MU',
  },
  {
    countryId: 100115,
    value: '52',
    nameEn: 'Mexico',
    name: '墨西哥',
    acronym: 'MX',
  },
  {
    countryId: 100116,
    value: '373',
    nameEn: 'Moldova, Republic of',
    name: '摩尔多瓦',
    acronym: 'MD',
  },
  {
    countryId: 100117,
    value: '377',
    nameEn: 'Monaco',
    name: '摩纳哥',
    acronym: 'MC',
  },
  {
    countryId: 100118,
    value: '976',
    nameEn: 'Mongolia',
    name: '蒙古',
    acronym: 'MN',
  },
  {
    countryId: 100119,
    value: '1664',
    nameEn: 'Montserrat Is',
    name: '蒙特塞拉特岛',
    acronym: 'MS',
  },
  {
    countryId: 100120,
    value: '212',
    nameEn: 'Morocco',
    name: '摩洛哥',
    acronym: 'MA',
  },
  {
    countryId: 100121,
    value: '258',
    nameEn: 'Mozambique',
    name: '莫桑比克',
    acronym: 'MZ',
  },
  {
    countryId: 100122,
    value: '264',
    nameEn: 'Namibia',
    name: '纳米比亚',
    acronym: 'NA',
  },
  {
    countryId: 100123,
    value: '674',
    nameEn: 'Nauru',
    name: '瑙鲁',
    acronym: 'NR',
  },
  {
    countryId: 100124,
    value: '977',
    nameEn: 'Nepal',
    name: '尼泊尔',
    acronym: 'NP',
  },
  {
    countryId: 100126,
    value: '31',
    nameEn: 'Netherlands',
    name: '荷兰',
    acronym: 'NL',
  },
  {
    countryId: 100127,
    value: '64',
    nameEn: 'New Zealand',
    name: '新西兰',
    acronym: 'NZ',
  },
  {
    countryId: 100128,
    value: '505',
    nameEn: 'Nicaragua',
    name: '尼加拉瓜',
    acronym: 'NI',
  },
  {
    countryId: 100129,
    value: '227',
    nameEn: 'Niger',
    name: '尼日尔',
    acronym: 'NE',
  },
  {
    countryId: 100130,
    value: '234',
    nameEn: 'Nigeria',
    name: '尼日利亚',
    acronym: 'NG',
  },
  {
    countryId: 100131,
    value: '850',
    nameEn: 'North Korea',
    name: '朝鲜',
    acronym: 'KP',
  },
  {
    countryId: 100132,
    value: '47',
    nameEn: 'Norway',
    name: '挪威',
    acronym: 'NO',
  },
  {
    countryId: 100133,
    value: '968',
    nameEn: 'Oman',
    name: '阿曼',
    acronym: 'OM',
  },
  {
    countryId: 100134,
    value: '92',
    nameEn: 'Pakistan',
    name: '巴基斯坦',
    acronym: 'PK',
  },
  {
    countryId: 100135,
    value: '507',
    nameEn: 'Panama',
    name: '巴拿马',
    acronym: 'PA',
  },
  {
    countryId: 100136,
    value: '675',
    nameEn: 'Papua New Cuinea',
    name: '巴布亚新几内亚',
    acronym: 'PG',
  },
  {
    countryId: 100137,
    value: '595',
    nameEn: 'Paraguay',
    name: '巴拉圭',
    acronym: 'PY',
  },
  {
    countryId: 100138,
    value: '51',
    nameEn: 'Peru',
    name: '秘鲁',
    acronym: 'PE',
  },
  {
    countryId: 100139,
    value: '63',
    nameEn: 'Philippines',
    name: '菲律宾',
    acronym: 'PH',
  },
  {
    countryId: 100140,
    value: '48',
    nameEn: 'Poland',
    name: '波兰',
    acronym: 'PL',
  },
  {
    countryId: 100141,
    value: '689',
    nameEn: 'French Polynesia',
    name: '法属玻利尼西亚',
    acronym: 'PF',
  },
  {
    countryId: 100142,
    value: '351',
    nameEn: 'Portugal',
    name: '葡萄牙',
    acronym: 'PT',
  },
  {
    countryId: 100143,
    value: '1787',
    nameEn: 'Puerto Rico',
    name: '波多黎各',
    acronym: 'PR',
  },
  {
    countryId: 100144,
    value: '974',
    nameEn: 'Qatar',
    name: '卡塔尔',
    acronym: 'QA',
  },
  {
    countryId: 100145,
    value: '262',
    nameEn: 'Reunion',
    name: '留尼旺',
    acronym: 'RE',
  },
  {
    countryId: 100146,
    value: '40',
    nameEn: 'Romania',
    name: '罗马尼亚',
    acronym: 'RO',
  },
  {
    countryId: 100147,
    value: '7',
    nameEn: 'Russia',
    name: '俄罗斯',
    acronym: 'RU',
  },
  {
    countryId: 100148,
    value: '1758',
    nameEn: 'Saint Lueia',
    name: '圣卢西亚',
    acronym: 'LC',
  },
  {
    countryId: 100149,
    value: '1784',
    nameEn: 'Saint Vincent',
    name: '圣文森特岛',
    acronym: 'VC',
  },
  {
    countryId: 100151,
    value: '685',
    nameEn: 'Samoa Western',
    name: '西萨摩亚',
    acronym: 'WS',
  },
  {
    countryId: 100152,
    value: '378',
    nameEn: 'San Marino',
    name: '圣马力诺',
    acronym: 'SM',
  },
  {
    countryId: 100153,
    value: '239',
    nameEn: 'Sao Tome and Principe',
    name: '圣多美和普林西比',
    acronym: 'ST',
  },
  {
    countryId: 100154,
    value: '966',
    nameEn: 'Saudi Arabia',
    name: '沙特阿拉伯',
    acronym: 'SA',
  },
  {
    countryId: 100155,
    value: '221',
    nameEn: 'Senegal',
    name: '塞内加尔',
    acronym: 'SN',
  },
  {
    countryId: 100156,
    value: '248',
    nameEn: 'Seychelles',
    name: '塞舌尔',
    acronym: 'SC',
  },
  {
    countryId: 100157,
    value: '232',
    nameEn: 'Sierra Leone',
    name: '塞拉利昂',
    acronym: 'SL',
  },
  {
    countryId: 100158,
    value: '65',
    nameEn: 'Singapore',
    name: '新加坡',
    acronym: 'SG',
  },
  {
    countryId: 100159,
    value: '421',
    nameEn: 'Slovakia',
    name: '斯洛伐克',
    acronym: 'SK',
  },
  {
    countryId: 100160,
    value: '386',
    nameEn: 'Slovenia',
    name: '斯洛文尼亚',
    acronym: 'SI',
  },
  {
    countryId: 100161,
    value: '677',
    nameEn: 'Solomon Is',
    name: '所罗门群岛',
    acronym: 'SB',
  },
  {
    countryId: 100162,
    value: '252',
    nameEn: 'Somali',
    name: '索马里',
    acronym: 'SO',
  },
  {
    countryId: 100163,
    value: '27',
    nameEn: 'South Africa',
    name: '南非',
    acronym: 'ZA',
  },
  {
    countryId: 100164,
    value: '34',
    nameEn: 'Spain',
    name: '西班牙',
    acronym: 'ES',
  },
  {
    countryId: 100165,
    value: '94',
    nameEn: 'Sri Lanka',
    name: '斯里兰卡',
    acronym: 'LK',
  },
  {
    countryId: 100166,
    value: '1758',
    nameEn: 'St.Lucia',
    name: '圣卢西亚',
    acronym: 'LC',
  },
  {
    countryId: 100167,
    value: '1784',
    nameEn: 'St.Vincent',
    name: '圣文森特',
    acronym: 'VC',
  },
  {
    countryId: 100168,
    value: '249',
    nameEn: 'Sudan',
    name: '苏丹',
    acronym: 'SD',
  },
  {
    countryId: 100169,
    value: '597',
    nameEn: 'Suriname',
    name: '苏里南',
    acronym: 'SR',
  },
  {
    countryId: 100170,
    value: '268',
    nameEn: 'Swaziland',
    name: '斯威士兰',
    acronym: 'SZ',
  },
  {
    countryId: 100171,
    value: '46',
    nameEn: 'Sweden',
    name: '瑞典',
    acronym: 'SE',
  },
  {
    countryId: 100172,
    value: '41',
    nameEn: 'Switzerland',
    name: '瑞士',
    acronym: 'CH',
  },
  {
    countryId: 100173,
    value: '963',
    nameEn: 'Syria',
    name: '叙利亚',
    acronym: 'SY',
  },
  {
    countryId: 100175,
    value: '992',
    nameEn: 'Tajikstan',
    name: '塔吉克斯坦',
    acronym: 'TJ',
  },
  {
    countryId: 100176,
    value: '255',
    nameEn: 'Tanzania',
    name: '坦桑尼亚',
    acronym: 'TZ',
  },
  {
    countryId: 100177,
    value: '66',
    nameEn: 'Thailand',
    name: '泰国',
    acronym: 'TH',
  },
  {
    countryId: 100178,
    value: '228',
    nameEn: 'Togo',
    name: '多哥',
    acronym: 'TG',
  },
  {
    countryId: 100179,
    value: '676',
    nameEn: 'Tonga',
    name: '汤加',
    acronym: 'TO',
  },
  {
    countryId: 100180,
    value: '1809',
    nameEn: 'Trinidad and Tobago',
    name: '特立尼达和多巴哥',
    acronym: 'TT',
  },
  {
    countryId: 100181,
    value: '216',
    nameEn: 'Tunisia',
    name: '突尼斯',
    acronym: 'TN',
  },
  {
    countryId: 100182,
    value: '90',
    nameEn: 'Turkey',
    name: '土耳其',
    acronym: 'TR',
  },
  {
    countryId: 100183,
    value: '993',
    nameEn: 'Turkmenistan',
    name: '土库曼斯坦',
    acronym: 'TM',
  },
  {
    countryId: 100184,
    value: '256',
    nameEn: 'Uganda',
    name: '乌干达',
    acronym: 'UG',
  },
  {
    countryId: 100185,
    value: '380',
    nameEn: 'Ukraine',
    name: '乌克兰',
    acronym: 'UA',
  },
  {
    countryId: 100186,
    value: '971',
    nameEn: 'United Arab Emirates',
    name: '阿拉伯联合酋长国',
    acronym: 'AE',
  },
  {
    countryId: 100187,
    value: '44',
    nameEn: 'United Kiongdom',
    name: '英国',
    acronym: 'GB',
  },
  {
    countryId: 100188,
    value: '1',
    nameEn: 'United States of America',
    name: '美国',
    acronym: 'US',
  },
  {
    countryId: 100189,
    value: '598',
    nameEn: 'Uruguay',
    name: '乌拉圭',
    acronym: 'UY',
  },
  {
    countryId: 100190,
    value: '998',
    nameEn: 'Uzbekistan',
    name: '乌兹别克斯坦',
    acronym: 'UZ',
  },
  {
    countryId: 100191,
    value: '58',
    nameEn: 'Venezuela',
    name: '委内瑞拉',
    acronym: 'VE',
  },
  {
    countryId: 100192,
    value: '84',
    nameEn: 'Vietnam',
    name: '越南',
    acronym: 'VN',
  },
  {
    countryId: 100193,
    value: '967',
    nameEn: 'Yemen',
    name: '也门',
    acronym: 'YE',
  },
  {
    countryId: 100194,
    value: '381',
    nameEn: 'Yugoslavia',
    name: '南斯拉夫',
    acronym: 'YU',
  },
  {
    countryId: 100195,
    value: '263',
    nameEn: 'Zimbabwe',
    name: '津巴布韦',
    acronym: 'ZW',
  },
  {
    countryId: 100196,
    value: '243',
    nameEn: 'Zaire',
    name: '扎伊尔',
    acronym: 'ZR',
  },
  {
    countryId: 100197,
    value: '260',
    nameEn: 'Zambia',
    name: '赞比亚',
    acronym: 'ZM',
  },
];
export { countries };
